### ISSUE TITLE
variables before for-loops

### ISSUE THREAD

**Issue by henchc** [dlab-berkeley/programming-fundamentals#8]
introduce variables before for-loops, just simple

my_var = "hello world"

echo $my_var

**Comment by natalieahn** [comment]
I think this is a great idea. The workshop is especially useful for learning how to use the shell, I think it would benefit from adding just a bit more about how to think of this as computer programming (and how some of the concepts will translate into future programming languages/workshops). Below are a few more tweaks I'd suggest, in line with adding the introduction of variables, which I think really support the objectives of the workshop. Throwing these out for discussion!

### Section 0-2 (under What it means to "know how to program"):

_I'd suggest adding a more concrete subsection on what programming languages have in common, before the list of ways they differ:_

#### What programming languages do:
- Programming involves giving instructions to a computer, to store, process, and/or retrieve information
- The instructions center around _things_ and _actions_, i.e. data and operations performed on data
- The things are items or values you refer to: a number, a name
  - You may deal with them one by one, or in lists, matrices, or more complex data structures
  - Later we'll show how you can use variables to store values as you work with them
- The actions are operations you tell the computer to perform: create, delete
  - You may feed them to the computer one by one, or combine them into longer procedures, often in the form of named functions
  - Later we'll show how you can repeat operations on multiple things, one of the major building blocks of functions and programs

[proceed into the list of how programming languages differ; this should also help in understanding the differences, like "Object-oriented", since it groups the things and actions together]

### Section 1-0 (at the end) or 1-1 (at the top, above Home Directories):

_I'd suggest a little tie-in to note how Bash uses _things_ and _actions_ to construct the types of commands used in the shell:_

#### A simple language for shell commands
- When we use the shell, we're giving the computer instructions in code, like with other programming languages
- Since the purpose here is to interact with the computer's file system, the _things_ are usually files or folders (directories)
- The _actions_ are usually simple commands we want to execute on files/folders, or commands to launch other programs stored in the computer's file system
- The syntax supports that intent. We give the computer instructions as a line in this form:
  - a command (the action)
  - optional arguments to tailor the command to how we want to use it (indicated by a "-" and letter or number)
  - then the file or folder (the thing) we want to operate on
  - sometimes followed by additional files or folders, if we're operating on more than one, or if we're moving/copying from one to another (the second being the destination)

[proceed into Home Directories...]

### Section 1-4 (above Loops):

_As Chris suggested, I think this section could be turned into "Variables and Loops", with the motivation that now we want to be able to repeat operations on multiple things_

#### Variables
- When we want to repeat operations on different things (e.g. files), we may not want to write a new set of commands with each different filename
- Instead, we can create variables, where we store a value (e.g. name or number), then use the variable in the operations we'd like to run
- Try typing:
  
  my_var="hello world"
  
  echo $my_var
- What happens when we type:
  
  echo my_var
- Now try:
  
  my_filename="draft.txt"
  
  cat $my_filename
- Now that we can refer to a file or folder using a placeholder variable we made up, we can repeat the same commands on a list of different filenames

[proceed into Loops...]

### Section 1-3: Pipes and Filters

_A final suggestion is that the above points add a bit of length, so we'd probably need to cut something out. I'd suggest cutting Section 1-3: Pipes and Filters. Chris, Alex and I noted briefly after the workshop that this might be the part students are least likely to need to use, at least as beginning programmers. Covering just a bit less ground in terms of complex shell commands might actually help them master/remember the critical basic commands they'll need to use in the later workshops (i.e. creating, moving, accessing, combining files and folders, and running scripts). In place of some of the more advanced shell operations, it would balance with just a bit more of the programming intuition, or the building block concepts they'll use to program across languages._

Thanks, excited to be part of the team!

**Comment by henchc** [comment]
I agree completely, go ahead and add your suggestions to the repo, but wait on the pipes and filters until we get more input since that would be a much larger change. I like this way of introducing for-loops better, especially since the for-loop uses the variable `filename`, so if we do your `filename ="draft.txt"` example, it will be much more clear, when we use it in the loop.

**Comment by natalieahn** [comment]
Great! Suggestions added to the repo. Thanks!

**Comment by henchc** [comment]
changes look really good @natalieahn , i've regenerated the pdfs, im closing this and opening a new issues about pipes.
