### ISSUE TITLE
remove, or abbreviate piping?

### ISSUE THREAD

**Issue by henchc** [dlab-berkeley/programming-fundamentals#9]
@natalieahn  has suggested we remove, move, or abbreviate piping, as it is not so much a "fundamental" of programming, as are variables and for loops, which I agree with. After all, we never get to scripts, abbreviating piping may help that, and scripts are quite fundamental in programming. And since we decided to go with Jupyter Notebooks, this would be their one exposure to scripts.

I think there may be a way to include piping shortly in the discussion of variables.

Any input is welcome

**Comment by rochelleterman** [comment]
To be honest, it's been awhile since I've taught the workshop so I can't remember how pipes / filters was received. I agree that loops are more fundamental. The one thing about pipes that may be important conceptually is the concept of stringing together a pipeline of data inputs/outputs. Perhaps you can abbreviate the lesson to touch on this concept if there's time...

In any case, I support whatever you guys decide to do.

**Comment by henchc** [comment]
For now, we've signifincantly abbreviated the original workshop, and introduced a short section on R and Python, geared toward the audience in our workshops. The old version is still preserved in its own branch.
